### ISSUE TITLE
Lack of support for special language structures(#() '())

### ISSUE THREAD

**Issue by codehz** [Cirru/cumulo-editor#1]

**Comment by jiyinyiyong** [comment]
It's actually implemented in https://github.com/Cirru/sepal.clj/blob/master/src/cirru/sepal.cljc and the lower level implementation is using https://github.com/brandonbloom/fipp/ . As a result I have to rely on FIPP to support it first.

Not sure how we can represent `#(f %)` pieces in FIPP. For `'()` I normally write `(list)`, or `(quote)` should be good too.

Do you have any ideas on extending `#(f %)`?

**Comment by codehz** [comment]
I think the `#(f x y)`(w/o `%`) can be transform to `fn [] (f x y)` for now until the FIPP support it directly.

----
It seems that it can also find an unused name (inside the expression) as a parameter, but this may reduce the readability of the generated code.

**Comment by jiyinyiyong** [comment]
I want to make Cirru as simple as possible for now. Currently it's based on Clojure and we know it generates Clojure so we can look up reference in Clojure and write Cirru directly. Once syntax-tree transformation is introduced, it becomes complicated.

**Comment by jiyinyiyong** [comment]
Did some experiments tonight, and it's:

```
[2:1]~cljs.user=> (with-out-str (pprint '#(+ %1 %2) {:width 40}))
"#(+ %1 %2)\n"
[2:1]~cljs.user=> '#(+ %1 %2)
(fn* [p1__3484# p2__3485#] (+ p1__3484# p2__3485#))
[2:1]~cljs.user=> '(fn* [x y] (+ x y))
(fn* [x y] (+ x y))
[2:1]~cljs.user=> (with-out-str (pprint '(fn* [x y] (+ x y))))
"#(+ %1 %2)\n"
[2:1]~cljs.user=> (with-out-str (pprint '(fn* [] (+ %1 %2))))
"#(+ %1 %2)\n"
```

I think there is a tricky solution for it...

**Comment by jiyinyiyong** [comment]
Should be good now. https://github.com/Cirru/sepal.clj/commits/master
Going to upgrade deps in cumulo-editor.

**Comment by jiyinyiyong** [comment]
@codehz are you actually use it BTW. I would like to take a look how you use it.
